#ifndef DCPDEFS_H
#define DCPDEFS_H

#define DCP_HEADER_SIZE 4

#define DCP_COMMAND_WRITE_REGISTER       0
#define DCP_COMMAND_READ_REGISTER        1
#define DCP_COMMAND_MULTI_WRITE_REGISTER 2
#define DCP_COMMAND_MULTI_READ_REGISTER  3

#define DCP_ESCAPE_CHARACTER 0x27

#endif /* !DCPDEFS_H */
